# Generated by Django 3.2.7 on 2021-09-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='hdm.png', upload_to='uploads/courses/'),
        ),
    ]
